routes:

collections:
  /:
    permalink: '{globals.permalinks}' # special 1.0 compatibility setting. See the docs for details.
    template:
      - home
      - index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
